name: Ruff

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run installing ruff and check
        uses: astral-sh/ruff-action@v3
        with:
          version-file: "./pyproject.toml"
          args: "check --diff"

      - name: Run format ruff
        run: ruff format --check --diff
